import Swift
print("Enter your name")
let name = readLine()
print("Enter your age")
let age = readLine()
print("Enter your class and division")
let classper = readLine()
print("Enter your school")
let school = readLine()
print("Hello \(name!). Your age is \(age!). Your class and division is \(classper!). Your school is \(school!)")