/*CREATE DATABASE School*/;
/*USE School*/;
CREATE TABLE Students(StudentID Integer, Name VarChar(20), Class VarChar(3), DOB Date, Email VarChar(30));
INSERT INTO Students VALUES(1,"Rahul Sharma","12A","2004-05-10","rahul@gmail.com"),(2,"Priya Verma","12B","2003-06-15","priya@gmail.com"),(3,"Amit Singh","12A","2004-07-20",NULL),(4,"Neha Gupta","12C","2003-08-25","neha@gmail.com");
ALTER TABLE Students ADD Primary Key(StudentID);
ALTER TABLE Students DROP Primary Key;
ALTER TABLE Students CHANGE Email ContactEmail VarChar(30);
ALTER TABLE Students ADD Address VarChar(50);
ALTER TABLE Students DROP DOB;
SELECT DISTINCT Class FROM Students;
SELECT * FROM Students WHERE Class="12A";
SELECT * FROM Students WHERE Class in ("12A","12B");
SELECT Name FROM Students ORDER By Name;
SELECT * FROM Students WHERE ContactEmail IS NOT NULL;
SELECT Name FROM Students WHERE Name LIKE "a%";
SELECT Name FROM Students WHERE Name LIKE "%a";
SELECT Name FROM Students WHERE LENGTH(Name)=4;
UPDATE Students SET Email="rahul_new@gmail.com" WHERE StudentID=1;
DELETE FROM Students WHERE StudentID=3;
/*DROP TABLE Students*/;
/*DROP DATABASE School*/;
