Length=int(input('Enter a Length measure'))
Breadth=int(input('Enter a Breadth measure'))
Height=int(input('Enter a Height measure'))
p=4*(Length+Breadth+Height)
tsa=2*((Length*Breadth)+(Length*Height)+(Breadth*Height))
lsa=2*Height*(Length+Breadth)
print (f'Perimeter of the Cuboid is {p} cm.')
print (f"Total Surface Area of the Cuboid is {tsa} sq.cm.")
print (f'Lateral Surface Area of the Cuboid is {lsa} sq.cm.')